dist: bionic
language: csharp
mono: none
dotnet: 2.2

install:
  - dotnet restore
script:
  - dotnet build -c Release
  - dotnet test -c Release test/ResultType.Tests/ResultType.Tests.csproj
  - dotnet test -c Release test/ResultType.Validation.Tests/ResultType.Validation.Tests.csproj
  
